name: Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: ./src

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Pack
        run: dotnet pack --configuration Release --no-build
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Publish to GitHub Packages
        run: dotnet nuget push bin/Release/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.DEPLOYMENT_TOKEN }}
        working-directory: ${{ env.PROJECT_PATH }}
