name: Run .NET Tests

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install .NET SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      # Restore dependencies for the solution
      - name: Restore dependencies
        run: dotnet restore Monsky.Fake.sln
        working-directory: ${{ vars.WORKING_DIRECTORY }}

      # Build the solution
      - name: Build solution
        run: dotnet build Monsky.Fake.sln --no-restore --configuration Release
        working-directory: ${{ vars.WORKING_DIRECTORY }}

      # Run tests
      - name: Run tests
        run: dotnet test Monsky.Fake.sln --no-build --verbosity normal --configuration Release
        working-directory: ${{ vars.WORKING_DIRECTORY }}
